import { describe, it, expect } from 'vitest';
import { LoopbackHub } from '../net/transport';
import { HostSession } from '../net/host';
import { ClientSession } from '../net/client';
import { HumanController } from '../entity';
import { Block } from '../blocks';

// Regression: the HostSession generates its spawn column locally but must settle its water
// (main.ts:1347 settles per-chunk for the host; the host session had no equivalent). Without
// the settle, the worldgen ocean water stays at wlevel 0 (unseeded), which waterSurfaceHeight
// maps to a 0-height quad per cell — the visible "stack of flat ocean surfaces" in the ?mp
// ocean. Assert the host's ocean water is seeded (wlevel >= 1, not 0) + host/client agree.
describe('host settles its spawn-column water (?mp=client loopback)', () => {
  it('seeds the ocean water + keeps host/client in sync', async () => {
    const hub = new LoopbackHub();
    const host = new HostSession(hub.connect('headless'), 1234, { withOwnPlayer: false });
    const a = new ClientSession(hub.connect('me'), 'me', new HumanController(new Set(['KeyW'])));
    const welcome = new Promise<void>((res) => { a.on('welcome', () => res()); });
    for (let t = 0; t < 40; t++) { host.tick(t); a.tick(t); hub.pump(t); }
    await welcome;
    for (let t = 40; t < 300; t++) { host.tick(t); a.tick(t); hub.pump(t); }

    // Scan the ocean near the spawn (the entity swims here) for Water cells + check wlevel.
    let waterCells = 0, zeroLevelHost = 0, mismatch = 0;
    for (let x = 0; x < 16; x++) for (let z = 32; z < 48; z++) for (let y = 24; y < 40; y++) {
      const hc = host.world.readCell(x, y, z);
      if (!hc || hc.block !== Block.Water) continue;
      waterCells++;
      if (hc.l === 0) zeroLevelHost++;
      const cc = a.world.readCell(x, y, z);
      const cl = cc ? cc.l : -1;
      const cb = cc ? cc.block : -1;
      if (hc.l !== cl || cb !== Block.Water) mismatch++;
    }
    expect(waterCells).toBeGreaterThan(0); // the scan area has ocean water
    expect(zeroLevelHost).toBe(0);         // every host water cell is seeded (wlevel >= 1), not 0
    expect(mismatch).toBe(0);              // host + client water state agree
  });

  // Regression (streamed chunks): the host settles only its spawn column in the constructor.
  // The rest of the world is generated by streaming (streamUpdate in host.tick); without a
  // per-chunk settle those chunks stay wlevel 0 while the spawn column is 7, and the client's
  // mesher emits internal top faces at the 7→0 seam ("extra faces in sections"). Assert the
  // STREAMED x-neighbour chunk (cx=1, cz=2) is also seeded + in sync with the client.
  it('seeds the streamed (non-spawn) chunks too', async () => {
    const hub = new LoopbackHub();
    const host = new HostSession(hub.connect('headless'), 1234, { withOwnPlayer: false });
    const a = new ClientSession(hub.connect('me'), 'me', new HumanController(new Set(['KeyW'])));
    const welcome = new Promise<void>((res) => { a.on('welcome', () => res()); });
    for (let t = 0; t < 40; t++) { host.tick(t); a.tick(t); hub.pump(t); }
    await welcome;
    for (let t = 40; t < 300; t++) { host.tick(t); a.tick(t); hub.pump(t); }

    // Scan the x-neighbour chunk (cx=1: x 16..31) of the spawn column (0,·,2).
    let waterCells = 0, zeroLevelHost = 0, mismatch = 0;
    for (let x = 16; x < 32; x++) for (let z = 32; z < 48; z++) for (let y = 24; y < 40; y++) {
      const hc = host.world.readCell(x, y, z);
      if (!hc || hc.block !== Block.Water) continue;
      waterCells++;
      if (hc.l === 0) zeroLevelHost++;
      const cc = a.world.readCell(x, y, z);
      const cl = cc ? cc.l : -1;
      if (hc.l !== cl) mismatch++;
    }
    expect(waterCells).toBeGreaterThan(0); // the streamed chunk has ocean water
    expect(zeroLevelHost).toBe(0);         // every streamed-chunk water cell is seeded, not 0
    expect(mismatch).toBe(0);              // host + client water state agree
  });
});